### ISSUE TITLE
Can't download anything 

### ISSUE THREAD

**Issue by astroskyoffical** [Magisk-Modules-Alt-Repo/chroot-distro#1]
Rooted.   Installed busybox module 

Installed your magisk modual. 

I run this and get this error for every distro.  
![Screenshot_20240312-113950_Termux](https://github.com/Magisk-Modules-Alt-Repo/chroot-distro/assets/101475363/d7e14a5e-a116-45c4-ad8b-ab204e7b95b4)

**Comment by astroskyoffical** [comment]
Ok It installed after I checked your scripts.     How can I view my desktop once I'm logged in?

**Comment by YasserNull** [comment]
read readme.md

**Comment by jjkola** [comment]
Maybe this could be closed as the issue was resolved?

**Comment by jjkola** [comment]
Decided to reopen this issue so that documentation can be fixed and refined, so that this problem is less likely to happen.
