### ISSUE TITLE
Ubuntu 24.04

### ISSUE THREAD

**Issue by MastaG** [Magisk-Modules-Alt-Repo/chroot-distro#10]
Please add Ubuntu 24.04, thx !

**Comment by jjkola** [comment]
There seems to be a PR for that against @YasserNull's own repository (https://github.com/YasserNull/chroot-distro/pull/1).

**Comment by MastaG** [comment]
I see, so is this repository dead now?
Can somebody please compile a module with @YasserNull's PR?

**Comment by MastaG** [comment]
Nevermind, I've applied your PR as a patch, and YasserNull's PR as well.
Thx for your work bro!

**Comment by jjkola** [comment]
Shouldn't this be left open as the PR has not been merged?

**Comment by jjkola** [comment]
Re-opened to merge the fix to this repo.
