### ISSUE TITLE
Restore restores distro to wrong directory

### ISSUE THREAD

**Issue by jjkola** [Magisk-Modules-Alt-Repo/chroot-distro#11]
Steps to reproduce:

1. Backup a distro
2. Uninstall the distro
3. Restore the distro

Expected outcome:
Distro is restored properly

Actual outcome:
Distro is restored to /data/local/chroot-distro/\<distroname\>/data/local/chroot-distro/\<distroname\>

**Comment by jjkola** [comment]
I have a fix ready in my fork (fix_backup_and_restore branch) for which I will create a PR after #7 has been merged.

**Comment by MastaG** [comment]
Perhaps you should just create a fork and create some action runner which pushes new releases on every commit :)

**Comment by jjkola** [comment]
This has been mostly scratching my own itch (I want to rescue a broken tablet to other uses) so I'm not entirely sure how much I will spend on this. But if there is enough interested I may take on this but before that I would like to see @YasserNull clarify the license (#12 ).

**Comment by YasserNull** [comment]
Thanks bro, I didn't notice

**Comment by jjkola** [comment]
Created a PR from the aforementioned branch.
