### ISSUE TITLE
No distro.tar.xz

### ISSUE THREAD

**Issue by Ranwiesiel** [Magisk-Modules-Alt-Repo/chroot-distro#2]
![Screenshot_20240331-102359_Termux.png](https://github.com/Magisk-Modules-Alt-Repo/chroot-distro/assets/87268415/2fa9be6b-2ef0-4b12-8851-865e5b30e65e)

How to fix this? How to download this file? Or is there any steps i missed?

**Comment by jjkola** [comment]
What is your device / environment?

**Comment by jjkola** [comment]
Closing this as inactive. If this is still an issue please create a new one with requested information.
