### ISSUE TITLE
distribution download error

### ISSUE THREAD

**Issue by sastreae** [Magisk-Modules-Alt-Repo/chroot-distro#3]
Connecting to github.com (20.201.28.151:443)
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer
Failed to download the Debian Rootfs.
rm: /data/local/chroot-distro/.rootfs/debian.tar.xz: No such file or directory

**Comment by jjkola** [comment]
@sastreae were you able fix this? there has been more reports of the same issue.

**Comment by jjkola** [comment]
@sastreae  Based on #9, updating busybox-ndk should fix this issue. Can you try that and report back?

**Comment by jjkola** [comment]
Closed as inactive.
