### ISSUE TITLE
Login Command not working

### ISSUE THREAD

**Issue by arpit64400** [Magisk-Modules-Alt-Repo/chroot-distro#31]
Input:- chroot-distro login ubuntu
Output:- chroot-distro - unknonwn parameters
try 'chroot-distro help' for more information

**Comment by jjkola** [comment]
Thanks for the report. I had noticed this bug but thought that it was related to how I called it. I have already a fix done for this but as I didn't realize that this is bigger problem, I haven't published the fix yet. I will try to publish the fix as soon as possible.
