### ISSUE TITLE
Unable to use sudo

### ISSUE THREAD

**Issue by Damglador** [Magisk-Modules-Alt-Repo/chroot-distro#37]
Distro: archlinux
Android: 14
Root by: KernelSU
So I installed module, rebooted, added alias to chroot-distro bin in Termux, downloaded Arch, installed Arch, logged in Arch (got a bunch of issues with PGP keys and resolv.conf, but that's unrelated), installed `sudo`, added a user with `useradd -m -G wheel -s /bin/bash damglador`. Logging in the user and trying to run `sudo` throws an error - `sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`. User is in sudoers group, otherwise it would throw a different error.

If it's a known issue that's not on the chroot-distro end, I would like to know how to fix it?

**Comment by jjkola** [comment]
Please see the project README, and especially the section about how to enable sudo. It is issue with how android mounts the volumes (for security). README provides a few possible alternatives to remedy the situation.
