### ISSUE TITLE
Broken resolv.conf on Arch

### ISSUE THREAD

**Issue by Damglador** [Magisk-Modules-Alt-Repo/chroot-distro#54]
Arch comes with /etc/resolv.conf that seems to be corrupted because it can't be read, network in the distro doesn't work because of that, I had to delete the file and create a new one with `nameserver 8.8.8.8`

**Comment by jjkola** [comment]
Thanks for the report, and sorry about late reply, I have been pretty busy lately. This sounds like an issue with permissions.

First, can you provide information about your device? Make and model, android version used, and do you have some custom rom installed? Also, can you attach the output of `chroot-distro env` here?

**Comment by Damglador** [comment]
Ulefone Armor 21
Android 14
Stock ROM with KernelSU root (perhaps that's the issue)

```
Script: /system/bin/chroot-distro
Version: 1.2.3
Versioncode: 11
md5 hash: e01c06a721bf7ea677ee5a3a2508da6d
Toybox version: toybox 0.8.9-android
busybox => '/system/bin/busybox'
Busybox version: BusyBox v1.36.1-osm0sis (2023-09-02 19:01:41 ADT) multi-call binary.
chroot => '/system/bin/chroot'
KernelSU installed (version not known)
Busybox for Android NDK Magisk module installed
Linux 5.10.205-android12-9-00027-g4d6c07fc6342-ab11525972 #1 SMP PREEMPT Mon Mar 4 18:49:33 UTC 2024 aarch64 Android
PATH=/data/data/com.termux/files/usr/bin:/system/bin:/system/bin:/system/xbin:/sbin:/sbin/bin
```

**Comment by jjkola** [comment]
Can you create a new Arch rootfs (you can/should backup the current one)? Then run the following commands inside the jail: `ls -lZ /etc/resolv.conf` and `ls -lZn /etc/resolv.conf`. What does those commands output?

**Comment by Damglador** [comment]
Deleted/uninstalled archlinux, but chroot-distro also doesn't seem to update status, list displays that it's installed and downloaded, while in reality it's not.

> Can you create a new Arch rootfs (you can/should backup the current one)? Then run the following commands inside the jail: `ls -lZ /etc/resolv.conf` and `ls -lZn /etc/resolv.conf`. What does those commands output?

[root@localhost ~]# ls -lZ /etc/resolv.conf
lrwxrwxrwx 1 root root ? 32 Dec  5 08:28 /etc/resolv.conf -> /run/systemd/resolve/resolv.conf
[root@localhost ~]# ls -lZn /etc/resolv.conf
lrwxrwxrwx 1 0 0 ? 32 Dec  5 08:28 /etc/resolv.conf -> /run/systemd/resolve/resolv.conf

**Comment by jjkola** [comment]
Can you check if `/run/systemd/resolve/resolv.conf` file is available? I would think that it would not be available by default, thus creating a broken link, which would explain why it does not work.

**Comment by Damglador** [comment]
> Can you check if `/run/systemd/resolve/resolv.conf` file is available? I would think that it would not be available by default, thus creating a broken link, which would explain why it does not work.

`/run` is empty

**Comment by jjkola** [comment]
Thanks. Since we already provide functionality to override the default config for resolv.conf this is clearly a bug with current implementation. I will try to provide a fix as soon as possible but I will not be able to provide any timelines for this.

**Comment by jjkola** [comment]
Fix has been released.
