### ISSUE TITLE
chroot-distro unmount command hangs unless using the '--force --all' options

### ISSUE THREAD

**Issue by anaxonda** [Magisk-Modules-Alt-Repo/chroot-distro#55]
When I run the `chroot-distro unmount` command it hangs, unless using the `--force --all` options. 

So far nothing bad happened, but is there a recommended way to unmount more gracefully?

**Comment by jjkola** [comment]
Thanks for the bug report. I have linked the relevant issue to this one. `unmount` command is not mandatory to run after use of `chroot-distro`. I added it as a helper to make it easier to test development changes. I just wanted to reset mounts without needing to reboot the device, or having to uninstall the chroot. But, I can see the value of using it to clean up the environment after use (outside of development process).

**Comment by jjkola** [comment]
@anaxonda Can you test the fix from the linked PR? With the changes lsof output (and other outputs) should work much quicker. You can create a development version by downloading the branch linked to PR and then creating package zip with help of the hacking guide in README.

**Comment by jjkola** [comment]
@defectly Can you also try the fix since you also experienced the problem?

**Comment by jjkola** [comment]
Also, if you are experiencing the problem can you guys run `chroot-distro env` and then call directly the lsof invocation used (most likely `busybox lsof`). I would also appreciate if you could run both lsof invocation and `chroot-distro unmount <distro>` through the `time` command, ie. `time busybox lsof` (if the invocation was for `busybox lsof`) and `time chroot-distro unmount <distro>`. This way we can have a better understanding of situation.

**Comment by anaxonda** [comment]
@jjkola I tried the fix, sorry for taking so long. Now it does not hang. Here is the output using `time` command. However it seems like it still doesn't unmount most directories? Is it running as intended?

````
1|:/data/data/com.termux/files/home # time chroot-distro unmount
distro is potentially running - if needed shutdown the distro, and unmount mounted folders

You can try running unmount again with -f(--force) option to automatically close/unmount files/folders mentioned below.
Please note, that using --force option may close more programs than intended, so use it with care.

open files under /data/local/chroot-distro/debian (which affects unmounting, there may be more):
17979   /data/local/chroot-distro/debian/usr/bin/ssh-agent      0       /data/local/chroot-distro/debian/dev/null
17979   /data/local/chroot-distro/debian/usr/bin/ssh-agent      1       /data/local/chroot-distro/debian/dev/null
17979   /data/local/chroot-distro/debian/usr/bin/ssh-agent      2       /data/local/chroot-distro/debian/dev/null
17984   /data/local/chroot-distro/debian/usr/bin/gpg-agent      0       /data/local/chroot-distro/debian/dev/null
17984   /data/local/chroot-distro/debian/usr/bin/gpg-agent      1       /data/local/chroot-distro/debian/dev/null
end of open files

mount points under /data/local/chroot-distro/debian (which affects unmounting, there may be more):
Not found
end of mount points

loopback devices under /data/local/chroot-distro/debian (which affects unmounting, there may be more):
Not found
end of loopback devices

If there is no open files, mount points trueor loopback devices,
then check for anonymous inodes and inotify watches
    0m00.99s real     0m00.41s user     0m00.67s system
````

**Comment by jjkola** [comment]
Thanks. `unmount` command is meant for unmounting mount points mounted when you log into the rootfs. It is assumed that the user takes care of his/her own mounts after use.

`--all` option was later added for the convenience of the user so that you don't need to manually unmount all of the mounts which reside within the rootfs.

`--force` was added so that user does not need to manually close programs which keep the mounts active, but you should use it with care as it may close more than intended. Because of this, it is advisable to call `unmount` command (with or without `--all`) first without `--force`, and only after reviewing the output force the unmounts.

I will try to create a new version next weekend but can't promise anything (I have been pretty busy IRL lately).

**Comment by jjkola** [comment]
Fix has been released.
