### ISSUE TITLE
Sudo error

### ISSUE THREAD

**Issue by DeraidSeven** [Magisk-Modules-Alt-Repo/chroot-distro#56]
Hey! I've got error while trying to use sudo in Debian chroot.
Here is error:

> deraid@localhost:~$ sudo
`sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`

I tried to use visudo and it doesnt work.

**Comment by sabamdarif** [comment]
> Hey! I've got error while trying to use sudo in Debian chroot. Here is error:
> 
> > deraid@localhost:~$ sudo
> > `sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?`
> 
> I tried to use visudo and it doesnt work.

same for me

**Comment by jjkola** [comment]
Thanks for the report. If you read the [How to enable ...](https://github.com/Magisk-Modules-Alt-Repo/chroot-distro#how-to-enable-) section from the README, there it is documented how you can circumvent the android security settings.
